
development:
  adapter: mysql
  encoding: utf8
  database: shopping_cart_development
  username: root
  password: isiri
  host: 127.0.0.1
production:
  adapter: mysql
  encoding: utf8
  database: shopping_cart
  username: root
  password: isiri
  host: 127.0.0.1
test:
  adapter: mysql
  encoding: utf8
  database: shopping_cart_test
  username: root
  password: isiri
  host: 127.0.0.1
